Set sandbox-path-permissions to '([exists "/"])
This apparently works around some bug in racket 5.2.  It is meant to
address this problem: when I have the bot evaluate

        "(dict-update '((a . 9) (b . 2) (a . 1)) 'a add1 0)"

It responds with

        <rudybot> *offby1: error: current-directory: `exists' access denied for /usr/local/src/rudybot/

It does indeed fix that problem, but it seems to have replaced it with
a new problem:

        error: car: expects argument of type <pair>; given #f

I have no idea what's causing that :-|